services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myApp
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: BDatos
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .env

volumes:
  db_data:

networks:
  app-network:
